---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Verifying ansible pre-requisites
  yum: name={{item}} state=present
  with_items:
  - libselinux-python
  when: ansible_os_family == "RedHat"

- name: Install Sendmail
  package: name={{ item }} state=present
  with_items:
    - sendmail
    - sendmail-cf

- name: Configure sendmail launch at startup
  service: name=sendmail enabled=yes

- name: Configure sendmail queue flush frequency (RedHat family)
  template:
     src="sendmail-sysconfig.j2"
     dest="{{ sendmailsysconfig_dest_path }}"
     owner=root
     group=root
     mode=0644
     backup=yes
  notify: Restart sendmail
  when: ansible_os_family == "RedHat"
  
- name: Configure sendmail queue flush frequency (Debian family)
  lineinfile: dest=/etc/init.d/sendmail state=present regexp='^DAEMON_ARGS=' line='DAEMON_ARGS="-q{{sendmailrelay_queue_flush_freq}}"'
  notify: Restart sendmail
  when: ansible_os_family == "Debian"
  

- name: Configure sendmail
  template:
     src="sendmail.mc.j2"
     dest="{{ sendmailmc_dest_path }}"
     owner=root
     group=root
     mode=0644
     backup=yes
  notify: Reconfigure sendmail