---
- name: Verifying ansible pre-requisites
  yum: name={{item}} state=present
  with_items:
  - libselinux-python

- name: Install Sendmail
  yum: name={{ item }} state=present
  with_items:
    - sendmail
    - sendmail-cf

- name: Configure sendmail launch at startup
  service: name=sendmail enabled=yes

- name: Configure sendmail queue flush frequency
  template:
     src="sendmail-sysconfig.j2"
     dest="{{ sendmailsysconfig_dest_path }}"
     owner=root
     group=root
     mode=0644
     backup=yes
  notify: Restart sendmail

- name: Configure sendmail
  template:
     src="sendmail.mc.j2"
     dest="{{ sendmailmc_dest_path }}"
     owner=root
     group=root
     mode=0644
     backup=yes
  notify: Reconfigure sendmail